# Generated by Django 4.2.20 on 2025-03-08 12:13

from django.db import migrations, models
import suite.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestTask',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('56f280b9-9808-47cc-b0b5-0b5d340e236e'), editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='任务名称')),
                ('case', models.FileField(upload_to=suite.models.get_case_path, verbose_name='用例文件')),
                ('status', models.IntegerField(choices=[(0, '未开始'), (-1, '初始化'), (-2, '出现错误'), (1, '进行中'), (2, '生成报告'), (3, '执行结束')], default=-1, verbose_name='任务状态')),
                ('is_processing', models.BooleanField(default=False, editable=False, verbose_name='是否正在执行')),
                ('is_pass', models.BooleanField(default=False, editable=False, verbose_name='是否通过')),
                ('has_report', models.BooleanField(default=False, editable=False, verbose_name='是否生成报告')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '测试任务',
                'verbose_name_plural': '测试任务',
            },
        ),
    ]
